-- مسار — القاعدة الأولى: جدول عام (id + data jsonb) لكل مجموعة كانت محلية
-- بـ IndexedDB (راجع COLLECTIONS في src/core/config.js)، بالإضافة لطبقة
-- حسابات/دخول مبسّطة (profiles فقط، بدون أدوار متعددة — كل حساب نشط له
-- وصول كامل، والإدمن فقط يدير الحسابات عبر Edge Function منفصلة).
--
-- تصميم "id + data jsonb" مقصود: يطابق شكل IndexedDB الحر (keyPath:"id")
-- تمامًا، فينتقل منطق كل ملفات *-service.js للسحابة بدون أي تعديل عليه —
-- فقط طبقة التخزين (local-runtime.js -> cloud-runtime.js) هي اللي تتغيّر.
--
-- تشغيل هذا الملف يدويًا عبر SQL Editor بلوحة تحكم مشروع Supabase الخاص
-- بمسار (وليس مشروع CCE إطلاقًا) — رفع الملف لـ GitHub وحده لا يطبّقه.

begin;

-- ── الحسابات والدخول ─────────────────────────────────────────────────────

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text not null default '',
  is_admin boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.masar_is_active_user()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active is true
  );
$$;

create or replace function public.masar_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_admin is true and is_active is true
  );
$$;

-- يترجم اسم مستخدم مُدخَل بشاشة الدخول إلى الإيميل الحقيقي عند auth.users —
-- التحقق من كلمة المرور نفسها يبقى بالكامل من مسؤولية Supabase Auth، هذه
-- الدالة فقط تحل الاسم المستعار قبل استدعاء /auth/v1/token.
create or replace function public.masar_resolve_login_identifier(p_identifier text)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_identifier text := trim(coalesce(p_identifier, ''));
  v_email text;
begin
  if v_identifier = '' then return null; end if;
  if position('@' in v_identifier) > 0 then return lower(v_identifier); end if;

  select p.email into v_email
  from public.profiles p
  where p.is_active is true
    and lower(split_part(p.email, '@', 1)) = lower(v_identifier)
  limit 1;

  return v_email;
end;
$$;

revoke all on function public.masar_resolve_login_identifier(text) from public;
grant execute on function public.masar_resolve_login_identifier(text) to anon, authenticated;
grant execute on function public.masar_is_active_user() to authenticated;
grant execute on function public.masar_is_admin() to authenticated;

-- كل حساب Auth جديد (يُنشأ دائمًا عبر admin-users Edge Function — ما فيه
-- تسجيل عام بالتطبيق) يحصل تلقائيًا على صف profiles مطابق.
create or replace function public.masar_handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, is_active)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''), true)
  on conflict (id) do update set email = excluded.email;
  return new;
end;
$$;

drop trigger if exists masar_on_auth_user_created on auth.users;
create trigger masar_on_auth_user_created
  after insert on auth.users
  for each row execute function public.masar_handle_new_auth_user();

alter table public.profiles enable row level security;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
  for select using (id = auth.uid() or public.masar_is_admin());

-- تعديل is_admin/is_active يمر فقط عبر admin-users Edge Function (بمفتاح
-- service_role اللي يتجاوز RLS) — هذه السياسة تسمح فقط بتحديث المستخدم
-- لبياناته البسيطة الخاصة (مثل full_name)، لا صلاحياته.
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());

grant select, update on public.profiles to authenticated;

-- سجل تدقيق بسيط لعمليات admin-users (إنشاء/تعطيل/إعادة تعيين كلمة مرور) —
-- تُكتب فيه فقط من الـ Edge Function بمفتاح service_role (يتجاوز RLS)، لذا
-- لا نحتاج سياسات RLS للكتابة؛ الإدمن فقط يقرأه.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  actor text,
  action text,
  table_name text,
  record_id text,
  before_data jsonb,
  after_data jsonb
);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs
  for select using (public.masar_is_admin());

grant select on public.audit_logs to authenticated;

-- ── تحديث updated_at تلقائيًا عند أي UPDATE ──────────────────────────────

create or replace function public.masar_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ── جدول عام لكل مجموعة بيانات (كانت IndexedDB object store محليًا) ──────

do $$
declare
  collection text;
  policy_name text;
  trigger_name text;
  collections text[] := array[
    'departmentPlanProjects', 'agendaStatus', 'actionProgress', 'followUpItems',
    'reminders', 'students', 'grades', 'termAverages', 'guidanceCases',
    'caseSessions', 'supportPlans', 'supportPlanActions', 'careerSessions',
    'importBatches', 'promotedSubjects', 'promotedImportBatches',
    'teacherSchedule', 'officeHours'
  ];
begin
  foreach collection in array collections loop
    -- %I quotes a single identifier atomically — it cannot be concatenated
    -- with literal suffix text inside the format string (that would emit
    -- e.g. "students"_rw, a syntax error), so build the composite name
    -- first and pass the whole string to %I.
    policy_name := collection || '_rw';
    trigger_name := collection || '_touch_updated_at';

    execute format($f$
      create table if not exists public.%I (
        id text primary key,
        data jsonb not null,
        updated_at timestamptz not null default now()
      )
    $f$, collection);

    execute format('alter table public.%I enable row level security', collection);

    execute format('drop policy if exists %I on public.%I', policy_name, collection);
    execute format($f$
      create policy %I on public.%I
        for all
        using (public.masar_is_active_user())
        with check (public.masar_is_active_user())
    $f$, policy_name, collection);

    execute format('grant select, insert, update, delete on public.%I to authenticated', collection);

    execute format('drop trigger if exists %I on public.%I', trigger_name, collection);
    execute format($f$
      create trigger %I
        before update on public.%I
        for each row execute function public.masar_touch_updated_at()
    $f$, trigger_name, collection);
  end loop;
end $$;

commit;
